---
title: "Clarke, Kornberg and Stewart (2000) 'A NOTE ON REFERENDUM VOTING AS POLITICAL CHOICE'"
date: "28.12.2014"
output: pdf_document
---

*Clarke, Harold D., Allan Kornberg, and Marianne C. Stewart. 2004. “Referendum Voting as Political Choice: The Case of Quebec.” British Journal of Political Science 34 (02): 345–55. doi:10.1017/S0007123404000092.*

*Abstract*
In an article published in thisJournal,Nadeau, Martin and Blais argue that perceptions of the costs and benefits
of alternative outcomes and general orientations to risk interact to affect voters' decisions in referendums on
fundamental political questions such as Quebec sovereignty. We use Nadeauet al.'s data to demonstrate that
their interaction-effects model is overly complex and suffers from serious multicollinearity difficulties. A
simpler main-effects model has virtually identical explanatory power and removes anomalous findings. We
also argue that their model is too simple because it omits variables such as party identification, feelings about
party leaders and government performance evaluations that voters use as heuristic devices to help them make
decisions when stakes are high and information about the costs and benefits of referendum outcomes is low.
We analyse a dataset that includes these variables and demonstrate that they have strong effects in a model
of referendum voting that controls for perceived costs and benefits of alternative referendum outcomes and
several other variables. Additionally, differences in the magnitudes of the perceived costs and perceived
benefits of alternative referendum outcomes are not statistically significant. This latter finding contradicts
widely cited experimental results in behavioural economics and related 'asymmetry' hypotheses concerning
the presumed status quobias in major referendums.

## Excerpt

"A simpler main-effects model has virtually identical explanatory power and removes anomalous findings. We also argue that their model is too simple because it omits variables such as party identification, feelings about
party leaders and government performance evaluations that voters use as heuristic devices to help them make
decisions when stakes are high and information about the costs and benefits of referendum outcomes is low." (abstract)

"To address the latter deficiency, we employ an alternative dataset generated by a panel
survey of the Quebec electorate conducted immediately before and after the 1995
sovereignty referendum.
These data enable us to specify a model of referendum voting
that assesses the impact of orientations towards party leaders, governmental performance
evaluations and party identifications, while controlling for several other potentially
influential variables including the perceived costs and benefits of alternative referendum
outcomes." (p. 346)

"As anticipated, party identifications, feelings
about party leaders and government performance evaluations have statistically significant
and substantively important effects in this model." (p. 347)

"The model has considerable explanatory power - the estimated R2
equals 0.77 and the
percentage of cases correctly classified is 87.6 per cent (see Table 1, interaction effects
model).
10
This latter figure represents a 76.1 per cent reduction in prediction error
compared to naively guessing that all cases are in the modal (vote no) category." (p. 347)

"If, as Nadeauet al. argue, perceived economic and linguistic costs and
benefits are crucially important in referendum voting, then one would anticipate that people
who assign a substantial probability to acatastrophiceconomic or linguistic outcome if
Quebec became sovereign, would vote No - regardless of their general orientation to risk." (p. 349)

"In the run-up to the 1995 referendum,
this protracted 'battle of the balance sheets' became intense, especially in the latter part
of the campaign when polls showed support for sovereignty was surging and that a Yes
majority was a genuine possibility." (p. 350)

"In contrast, people who feared that sovereignty would prove costly
were apt to vote No, as were those who saw significant benefits to maintaining thestatus
quo." (p.352)

"Our model tells another story as well. Controlling for the effects of the cost-benefit
perceptions and several other predictors, we find that feelings about party leaders, party
identifications and governing party performance evaluations have strong explanatory
power." (p. 354)

## Empirics

They replicate Nadeau, Martin and Blais, 1999 which sees questions abou perceived cost as major independent variable.

Model parameters are estimated using data
gathered in a panel survey of the Quebec electorate
conducted before and after the October 30, 1995 sovereignty referendum.

"Control variables in their model include age, education, gender, income, language, and self-identification as a Quebecer or a Canadian." (p. 3)


